[send_msg]
# 发送钉钉整体报告开关
send_flag = True
# 发送钉钉单个用例报告开关
single_send_flag = True
# 个人钉钉token：默认一个个人测试群机器人，可依据个人进行修改
dingding_token = f53f6f864a88872b59c7eab5393350bff412f6a627cbadc136824cda21ed4860

# 单条报告默认钉钉机器人，默认：小程序自动化用例执行结果，勿动
single_dingding_token = 22ebe571cf8b5b82da497827d848d25cdc9ca0a3fc42b62b9caad583f3ffd06f
# 整体报告默认钉钉机器人，默认：核心必测告警群，勿动
total_dingding_token = 42765bcec4dbfa0af13a0c115804e6a97461ceae5c5b732508cd5681ad487bf5


[write_db]
# 是否写入数据库开关
# write_db_flag = False
write_db_flag = True
[environment]
env = PathConfig.ZJY